// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmeyqhreseuvkrdowzfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtZXlxaHJlc2V1dmtyZG93emZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0NDQ3ODEsImV4cCI6MjA1MjAyMDc4MX0.Kme87ieJKA9sMviOlZhARnKValg4OLE00FvnF5_g7Gw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);